package com.shiva.magics.data.repository

import com.shiva.magics.data.local.AppDatabase
import com.shiva.magics.data.local.QuestionEntity
import com.shiva.magics.data.local.TestHistoryEntity
import com.shiva.magics.data.local.TestWithQuestions
import com.shiva.magics.data.local.ExamTemplateEntity
import com.shiva.magics.data.local.MockExamHistoryEntity
import com.shiva.magics.data.local.MarketplaceExamEntity
import com.shiva.magics.data.local.CreatorRevenueEntity
import com.shiva.magics.data.local.TopicMasteryEntity
import com.shiva.magics.data.local.StudyPlanEntity
import com.shiva.magics.data.local.RevisionQueueEntity
import com.shiva.magics.data.local.DailyTaskEntity
import com.shiva.magics.data.model.Citation
import com.shiva.magics.data.model.Question
import com.shiva.magics.data.model.VerificationStatus
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.withContext
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

class TestRepository(private val db: AppDatabase) {
    private val dao = db.testHistoryDao()
    private val json = Json { ignoreUnknownKeys = true }
    private val streakEngine = com.shiva.magics.util.StreakEngine(db.studyStreakDao())

    fun getAllTests(): Flow<List<TestHistoryEntity>> = dao.getAllTests()

    fun getActiveStudyPlan(): Flow<StudyPlanEntity?> = db.studyPlanDao().getActivePlan()
    
    fun getRevisionQueue(): Flow<List<RevisionQueueEntity>> = db.revisionQueueDao().getFullQueue()

    fun getTasksForDay(start: Long, end: Long): Flow<List<DailyTaskEntity>> = db.dailyTaskDao().getTasksForDay(start, end)

    fun getLatestInsight(): Flow<com.shiva.magics.data.local.DailyInsightEntity?> = db.dailyInsightDao().getLatestInsight()

    fun getReferrals(userId: String): Flow<List<com.shiva.magics.data.local.ReferralEntity>> = db.referralDao().getReferralsByInviter(userId)

    suspend fun getReferralCount(userId: String): Int = db.referralDao().getReferralCount(userId)

    suspend fun processReferral(inviterId: String, inviteeId: String) {
        com.shiva.magics.util.ReferralManager.processReferral(db.referralDao(), inviterId, inviteeId)
    }

    fun getPendingAutoTests(): Flow<List<com.shiva.magics.data.local.AutoGeneratedTestEntity>> = db.autoGeneratedTestDao().getPendingAutoTests()

    fun getAllFeatureFlags(): Flow<List<com.shiva.magics.data.local.FeatureFlagEntity>> = db.featureFlagDao().getAllFlags()

    suspend fun getAllFeatureFlagsOnce(): List<com.shiva.magics.data.local.FeatureFlagEntity> = db.featureFlagDao().getAllFlagsOnce()

    suspend fun isFeatureEnabled(name: String): Boolean {
        return com.shiva.magics.util.ConfigManager.isFeatureEnabled(db.featureFlagDao(), name)
    }

    suspend fun setFeatureFlag(name: String, enabled: Boolean) {
        db.featureFlagDao().setFeatureFlag(com.shiva.magics.data.local.FeatureFlagEntity(name, enabled))
    }

    suspend fun generateDailyInsight() {
        com.shiva.magics.util.DailyInsightGenerator.generate(db)
    }

    suspend fun runAutonomousLoop(geminiService: com.shiva.magics.data.remote.GeminiService) {
        com.shiva.magics.util.AutonomousAgent.runAutonomousLoop(db, this, geminiService)
    }

    suspend fun getStudyStreak(): com.shiva.magics.data.local.StudyStreakEntity? = db.studyStreakDao().getStreak()

    suspend fun updateTaskCompletion(taskId: String, completed: Boolean) {
        db.dailyTaskDao().updateCompletion(taskId, completed)
        if (completed) {
            streakEngine.onActivityDetected()
        }
    }

    suspend fun syncStreak(geminiService: com.shiva.magics.data.remote.GeminiService? = null) {
        streakEngine.syncStreakStatus()
        generateDailyInsight()
        geminiService?.let { runAutonomousLoop(it) }
    }

    fun getExamTemplates(): Flow<List<ExamTemplateEntity>> = db.examSimulationDao().getAllTemplates()
    
    fun getExamHistory(): Flow<List<MockExamHistoryEntity>> = db.examSimulationDao().getExamHistory()

    suspend fun saveExamTemplate(template: ExamTemplateEntity) {
        db.examSimulationDao().insertTemplate(template)
    }

    fun getPublicExams(): Flow<List<MarketplaceExamEntity>> = db.marketplaceDao().getPublicExams()
    
    fun getExamsByCreator(creatorId: String): Flow<List<MarketplaceExamEntity>> = db.marketplaceDao().getExamsByCreator(creatorId)

    suspend fun publishExam(exam: MarketplaceExamEntity) {
        db.marketplaceDao().publishExam(exam)
    }

    suspend fun getCreatorRevenue(creatorId: String): CreatorRevenueEntity? = db.marketplaceDao().getRevenue(creatorId)

    fun getTestWithQuestions(id: Long): Flow<TestWithQuestions> =
        dao.getTestWithQuestions(id)

    suspend fun saveTest(title: String, category: String, questions: List<Question>, timeLimitSeconds: Int? = null): Long =
        withContext(Dispatchers.IO) {
            val testId = dao.insertTest(
                TestHistoryEntity(
                    title = title,
                    category = category,
                    questionCount = questions.size,
                    timeLimitSeconds = timeLimitSeconds
                )
            )
            dao.insertQuestions(
                questions.mapIndexed { i, q ->
                    QuestionEntity(
                        testId = testId,
                        questionIndex = i,
                        questionText = q.questionText,
                        optionsJson = json.encodeToString(q.options),
                        correctAnswerIndex = q.correctAnswerIndex,
                        topic = q.topic,
                        citationJson = q.citation?.let { json.encodeToString(it) },
                        pageNumber = q.citation?.pageNumber,
                        verificationStatus = q.verificationStatus.name,
                        trustScore = q.trustScore,
                        verifiedAt = q.verifiedAt
                    )
                }
            )
            testId
        }

    suspend fun updateBestScore(id: Long, score: Int, total: Int, wrong: Int) =
        withContext(Dispatchers.IO) {
            dao.updateLastTaken(id, System.currentTimeMillis())
            dao.updateBestScoreIfBetter(
                id = id,
                score = score,
                percent = if (total > 0) score.toFloat() / total * 100f else 0f,
                wrong = wrong
            )
            streakEngine.onActivityDetected()
            generateDailyInsight()
            db.autoGeneratedTestDao().markCompleted(id)
        }

    suspend fun submitTestTelemetry(
        reviewItems: List<com.shiva.magics.data.model.ReviewItem>,
        elapsedSeconds: Int
    ) {
        com.shiva.magics.util.MasteryTracker.processTestSubmission(
            reviewItems = reviewItems,
            elapsedSeconds = elapsedSeconds,
            testDao = db.testHistoryDao(),
            masteryDao = db.topicMasteryDao(),
            weakTopicDao = db.weakTopicDao(),
            predictionDao = db.performancePredictionDao(),
            studyPlanDao = db.studyPlanDao(),
            revisionQueueDao = db.revisionQueueDao(),
            dailyTaskDao = db.dailyTaskDao()
        )
    }

    suspend fun deleteTest(id: Long) = withContext(Dispatchers.IO) {
        dao.deleteQuestionsForTest(id)
        dao.deleteTest(id)
    }

    suspend fun renameTest(id: Long, newTitle: String) = withContext(Dispatchers.IO) {
        dao.updateTestTitle(id, newTitle)
    }

    suspend fun updateTestCategory(id: Long, newCategory: String) = withContext(Dispatchers.IO) {
        dao.updateTestCategory(id, newCategory)
    }

    suspend fun getQuestionsForTest(id: Long): List<Question> = withContext(Dispatchers.IO) {
        dao.getQuestionsForTest(id).map { it.toQuestion() }
    }

    suspend fun updateQuestions(id: Long, questions: List<Question>) = withContext(Dispatchers.IO) {
        dao.deleteQuestionsForTest(id)
        dao.updateQuestionCount(id, questions.size)
        dao.insertQuestions(
            questions.mapIndexed { i, q ->
                QuestionEntity(
                    testId = id,
                    questionIndex = i,
                    questionText = q.questionText,
                    optionsJson = json.encodeToString(q.options),
                    correctAnswerIndex = q.correctAnswerIndex,
                    topic = q.topic,
                    citationJson = q.citation?.let { json.encodeToString(it) },
                    pageNumber = q.citation?.pageNumber,
                    verificationStatus = q.verificationStatus.name,
                    trustScore = q.trustScore,
                    verifiedAt = q.verifiedAt
                )
            }
        )
    }

    suspend fun deleteAllTests() = withContext(Dispatchers.IO) {
        dao.deleteAllQuestions()
        dao.deleteAllTests()
    }

    // Convert QuestionEntity back to Question
    fun QuestionEntity.toQuestion(): Question = Question(
        questionText = questionText,
        options = json.decodeFromString(optionsJson),
        correctAnswerIndex = correctAnswerIndex,
        topic = topic,
        citation = citationJson?.let { runCatching { json.decodeFromString<Citation>(it) }.getOrNull() },
        verificationStatus = runCatching { VerificationStatus.valueOf(verificationStatus) }.getOrDefault(VerificationStatus.UNVERIFIED),
        trustScore = trustScore,
        verifiedAt = verifiedAt
    )

    fun buildShareJson(questions: List<Question>, title: String): String {
        val jsonQuestions = questions.map { q ->
            kotlinx.serialization.json.buildJsonObject {
                put("questionText", kotlinx.serialization.json.JsonPrimitive(q.questionText))
                put("options", kotlinx.serialization.json.buildJsonArray { q.options.forEach { add(kotlinx.serialization.json.JsonPrimitive(it)) } })
                put("correctAnswerIndex", kotlinx.serialization.json.JsonPrimitive(q.correctAnswerIndex))
            }
        }
        return kotlinx.serialization.json.buildJsonObject {
            put("title", kotlinx.serialization.json.JsonPrimitive(title))
            put("questions", kotlinx.serialization.json.JsonArray(jsonQuestions))
        }.toString()
    }
}
