package com.shiva.magics.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import com.shiva.magics.data.local.TestHistoryEntity
import com.shiva.magics.data.model.Question
import com.shiva.magics.data.repository.TestRepository
import com.shiva.magics.data.local.RevisionQueueEntity
import com.shiva.magics.data.local.StudyPlanEntity
import com.shiva.magics.data.local.DailyTaskEntity
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.launch
import java.util.Calendar

class HomeViewModel(private val repository: TestRepository) : ViewModel() {

    val dailyTasks: StateFlow<List<DailyTaskEntity>> by lazy {
        val calendar = Calendar.getInstance()
        calendar.set(Calendar.HOUR_OF_DAY, 0)
        calendar.set(Calendar.MINUTE, 0)
        val start = calendar.timeInMillis
        calendar.set(Calendar.HOUR_OF_DAY, 23)
        calendar.set(Calendar.MINUTE, 59)
        val end = calendar.timeInMillis
        
        repository.getTasksForDay(start, end)
            .stateIn(
                scope = viewModelScope,
                started = SharingStarted.WhileSubscribed(5_000),
                initialValue = emptyList()
            )
    }

    val activeStudyPlan: StateFlow<StudyPlanEntity?> = repository
        .getActiveStudyPlan()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = null
        )

    val revisionQueue: StateFlow<List<RevisionQueueEntity>> = repository
        .getRevisionQueue()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = emptyList()
        )


    val tests: StateFlow<List<TestHistoryEntity>> = repository
        .getAllTests()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = emptyList()
        )

    private val _studyStreak = kotlinx.coroutines.flow.MutableStateFlow<com.shiva.magics.data.local.StudyStreakEntity?>(null)
    val studyStreak = _studyStreak.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), null)

    val dailyInsight: StateFlow<com.shiva.magics.data.local.DailyInsightEntity?> = repository
        .getLatestInsight()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = null
        )

    val autoTests: StateFlow<List<com.shiva.magics.data.local.AutoGeneratedTestEntity>> = repository
        .getPendingAutoTests()
        .stateIn(
            scope = viewModelScope,
            started = SharingStarted.WhileSubscribed(5_000),
            initialValue = emptyList()
        )

    private val _referralCount = kotlinx.coroutines.flow.MutableStateFlow(0)
    val referralCount = _referralCount.asStateFlow()

    private val _isReferralEnabled = kotlinx.coroutines.flow.MutableStateFlow(true)
    val isReferralEnabled = _isReferralEnabled.asStateFlow()

    init {
        viewModelScope.launch {
            _studyStreak.value = repository.getStudyStreak()
            _referralCount.value = repository.getReferralCount("default_user")
            _isReferralEnabled.value = repository.isFeatureEnabled(com.shiva.magics.util.ConfigManager.FEATURE_REFERRALS)
        }
    }

    fun shareReferral(context: android.content.Context) {
        com.shiva.magics.util.ReferralManager.shareReferralLink(context, "default_user")
    }

    fun deleteTest(id: Long) {
        viewModelScope.launch { repository.deleteTest(id) }
    }

    fun renameTest(id: Long, newTitle: String) {
        viewModelScope.launch { repository.renameTest(id, newTitle) }
    }

    fun updateTestCategory(id: Long, newCategory: String) {
        viewModelScope.launch { repository.updateTestCategory(id, newCategory) }
    }

    fun toggleTaskCompletion(taskId: String, completed: Boolean) {
        viewModelScope.launch { repository.updateTaskCompletion(taskId, completed) }
    }

    suspend fun getQuestionsForTest(id: Long): List<Question> {
        return repository.getQuestionsForTest(id)
    }

    fun updateQuestions(id: Long, questions: List<Question>) {
        viewModelScope.launch { repository.updateQuestions(id, questions) }
    }

    // Factory for manual DI (no Hilt)
    class Factory(private val repository: TestRepository) : ViewModelProvider.Factory {
        override fun <T : ViewModel> create(modelClass: Class<T>): T {
            @Suppress("UNCHECKED_CAST")
            return HomeViewModel(repository) as T
        }
    }
}
