/**
 * YouTube Ingestion Engine Types
 * Production type definitions for YouTube transcript acquisition, normalization,
 * chunking, timestamp preservation, evidence grounding, and verification.
 */

import { CanonicalQuestion } from '../../../types/canonicalQuestion';

export interface YouTubeTranscriptSegment {
  start: number; // in seconds (e.g. 14.5)
  duration: number; // in seconds (e.g. 3.2)
  end: number; // in seconds (start + duration)
  text: string;
  formattedStart: string; // e.g. "00:14" or "01:14:05"
  formattedEnd: string; // e.g. "00:17"
  confidence?: number;
}

export interface YouTubeCaptionTrack {
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
  baseUrl?: string;
  vssId?: string;
  format?: 'json3' | 'xml' | 'vtt' | 'text';
}

export interface YouTubeVideoMetadata {
  videoId: string;
  title: string;
  author: string;
  authorUrl?: string;
  durationSeconds?: number;
  thumbnailUrl?: string;
  availableLanguages: string[];
  isPrivateOrDeleted?: boolean;
  captionsAvailable: boolean;
  publishedDate?: string;
  description?: string;
}

export interface YouTubeTranscriptResult {
  videoId: string;
  title: string;
  metadata: YouTubeVideoMetadata;
  captionType: 'MANUAL' | 'AUTOMATIC' | 'PROVIDER';
  language: string;
  segments: YouTubeTranscriptSegment[];
  rawText: string;
  normalizedText: string;
  version: string;
  fetchedAt: number;
}

export interface YouTubeSemanticChunk {
  chunkIndex: number; // 1-indexed
  title: string;
  startTime: number;
  endTime: number;
  formattedStart: string;
  formattedEnd: string;
  segments: YouTubeTranscriptSegment[];
  text: string;
  tokenCountApprox: number;
}

export type YouTubeFailureReason =
  | 'SOURCE_UNAVAILABLE'
  | 'PRIVATE_OR_DELETED'
  | 'TRANSCRIPT_DISABLED'
  | 'RATE_LIMITED'
  | 'UNSUPPORTED_LANGUAGE'
  | 'INVALID_URL'
  | 'SSRF_BLOCKED'
  | 'PROVIDER_ERROR';

export interface YouTubeProgress {
  stage:
    | 'VALIDATING'
    | 'FETCHING_METADATA'
    | 'FETCHING_TRANSCRIPT'
    | 'NORMALIZING'
    | 'CHUNKING'
    | 'GENERATING'
    | 'VALIDATING_QUESTIONS'
    | 'DEDUPLICATING'
    | 'COMPLETED';
  message: string;
  percentage: number;
  chunkIndex?: number;
  totalChunks?: number;
  questionsGenerated?: number;
}

export interface YouTubeQuestionEvidence {
  verified: boolean;
  confidence: number;
  sourceExcerpt: string;
  timestamp: string;
  timestampSeconds: number;
  reasons: string[];
  hallucinatedTerms?: string[];
}

export interface YouTubeIngestionOptions {
  requestedCount?: number;
  difficulty?: 'EASY' | 'MEDIUM' | 'HARD' | 'COMPETITIVE' | string;
  chunkSizeMinutes?: number; // default: 6 minutes
  overlapSeconds?: number; // default: 20 seconds
  preferredLanguage?: string; // default: 'en'
  mockTranscriptResult?: YouTubeTranscriptResult;
  mockAiGenerator?: (chunk: YouTubeSemanticChunk, count: number) => Promise<CanonicalQuestion[]>;
  onProgress?: (progress: YouTubeProgress) => void;
}

export interface YouTubeIngestionResult {
  success: boolean;
  videoId: string;
  title: string;
  metadata: YouTubeVideoMetadata;
  transcriptSummary: {
    totalDuration: number;
    segmentCount: number;
    chunkCount: number;
    captionType: 'MANUAL' | 'AUTOMATIC' | 'PROVIDER';
    language: string;
    wordCount: number;
  };
  questions: CanonicalQuestion[];
  chunks: YouTubeSemanticChunk[];
  groundingFidelityScore: number; // 0.0 to 1.0
  latencyMs: number;
  cached: boolean;
  error?: {
    code: YouTubeFailureReason;
    message: string;
    details?: string;
  };
}
