package com.shiva.magics.data.local

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase

@Database(
    entities = [TestHistoryEntity::class, QuestionEntity::class, OfflineAssignmentEntity::class, TopicMasteryEntity::class, WeakTopicEntity::class, PerformancePredictionEntity::class, StudyPlanEntity::class, RevisionQueueEntity::class, DailyTaskEntity::class, ExamTemplateEntity::class, MockExamHistoryEntity::class, ExamIntegrityEventEntity::class, ExamSessionEntity::class, ExamTimerStateEntity::class, ExamAnalyticsEntity::class, MarketplaceExamEntity::class, CreatorRevenueEntity::class, MarketplaceInteractionEntity::class, StudyStreakEntity::class, DailyInsightEntity::class, AutoGeneratedTestEntity::class, AICostUsageEntity::class, ReferralEntity::class, FeatureFlagEntity::class],
    version = 25,
    exportSchema = false
)
abstract class AppDatabase : RoomDatabase() {
    abstract fun testHistoryDao(): TestHistoryDao
    abstract fun offlineAssignmentDao(): OfflineAssignmentDao
    abstract fun topicMasteryDao(): TopicMasteryDao
    abstract fun weakTopicDao(): WeakTopicDao
    abstract fun performancePredictionDao(): PerformancePredictionDao
    abstract fun studyPlanDao(): StudyPlanDao
    abstract fun revisionQueueDao(): RevisionQueueDao
    abstract fun dailyTaskDao(): DailyTaskDao
    abstract fun examSimulationDao(): ExamSimulationDao
    abstract fun examIntegrityDao(): ExamIntegrityDao
    abstract fun examAnalyticsDao(): ExamAnalyticsDao
    abstract fun marketplaceDao(): MarketplaceDao
    abstract fun studyStreakDao(): StudyStreakDao
    abstract fun dailyInsightDao(): DailyInsightDao
    abstract fun autoGeneratedTestDao(): AutoGeneratedTestDao
    abstract fun aiCostDao(): AICostDao
    abstract fun referralDao(): ReferralDao
    abstract fun featureFlagDao(): FeatureFlagDao

    companion object {
        @Volatile private var INSTANCE: AppDatabase? = null

        fun getDatabase(context: Context): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                Room.databaseBuilder(
                    context.applicationContext,
                    AppDatabase::class.java,
                    "magics_database"
                )
                    .addMigrations(MIGRATION_1_2, MIGRATION_2_3, MIGRATION_3_4, MIGRATION_4_5, MIGRATION_5_6, MIGRATION_6_7, MIGRATION_7_8, MIGRATION_8_9, MIGRATION_9_10, MIGRATION_10_11, MIGRATION_11_12, MIGRATION_12_13, MIGRATION_13_14, MIGRATION_14_15, MIGRATION_15_16, MIGRATION_16_17, MIGRATION_17_18, MIGRATION_18_19, MIGRATION_19_20, MIGRATION_20_21, MIGRATION_21_22, MIGRATION_22_23, MIGRATION_23_24, MIGRATION_24_25)
                    .build().also { INSTANCE = it }
            }
        }

        private val MIGRATION_1_2 = object : androidx.room.migration.Migration(1, 2) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE test_history ADD COLUMN timeLimitSeconds INTEGER")
            }
        }

        private val MIGRATION_2_3 = object : androidx.room.migration.Migration(2, 3) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE test_history ADD COLUMN wrongAnswers INTEGER")
            }
        }

        private val MIGRATION_3_4 = object : androidx.room.migration.Migration(3, 4) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                try {
                    database.execSQL("ALTER TABLE test_history ADD COLUMN bestScorePercent REAL DEFAULT NULL")
                } catch (e: Exception) {
                    android.util.Log.w("DB_MIGRATE", "Column bestScorePercent already exists, skipping safely.")
                }
            }
        }

        private val MIGRATION_4_5 = object : androidx.room.migration.Migration(4, 5) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("ALTER TABLE questions ADD COLUMN topic TEXT DEFAULT NULL")
            }
        }
        
        private val MIGRATION_5_6 = object : androidx.room.migration.Migration(5, 6) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `offline_assignments` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `assignmentId` TEXT NOT NULL, `score` INTEGER NOT NULL, `total` INTEGER NOT NULL, `isSynced` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL)")
            }
        }

        private val MIGRATION_6_7 = object : androidx.room.migration.Migration(6, 7) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                // Day 1: Evidence Engine migration
                database.execSQL("ALTER TABLE questions ADD COLUMN citationJson TEXT DEFAULT NULL")
                database.execSQL("ALTER TABLE questions ADD COLUMN pageNumber INTEGER DEFAULT NULL")
                database.execSQL("ALTER TABLE questions ADD COLUMN verificationStatus TEXT NOT NULL DEFAULT 'UNVERIFIED'")
                database.execSQL("ALTER TABLE questions ADD COLUMN trustScore REAL NOT NULL DEFAULT 0.0")
                database.execSQL("ALTER TABLE questions ADD COLUMN verifiedAt INTEGER DEFAULT NULL")
                
                // Indices for scaling / searching
                database.execSQL("CREATE INDEX IF NOT EXISTS index_questions_pageNumber ON questions(pageNumber)")
                database.execSQL("CREATE INDEX IF NOT EXISTS index_questions_verificationStatus ON questions(verificationStatus)")
                database.execSQL("CREATE INDEX IF NOT EXISTS index_questions_trustScore ON questions(trustScore)")
            }
        }
        
        private val MIGRATION_7_8 = object : androidx.room.migration.Migration(7, 8) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `topic_mastery` (`topic` TEXT NOT NULL, `totalAttempts` INTEGER NOT NULL, `correctAttempts` INTEGER NOT NULL, `masteryLevel` REAL NOT NULL, `averageResponseTimeMs` INTEGER NOT NULL, `averageTrustScore` REAL NOT NULL, `lastAttemptAt` INTEGER NOT NULL, PRIMARY KEY(`topic`))")
            }
        }

        private val MIGRATION_8_9 = object : androidx.room.migration.Migration(8, 9) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `weak_topics` (`topic` TEXT NOT NULL, `riskLevel` TEXT NOT NULL, `masteryScore` REAL NOT NULL, `trendDirection` TEXT NOT NULL, `recommendedAction` TEXT NOT NULL, `lastDetectedAt` INTEGER NOT NULL, PRIMARY KEY(`topic`))")
            }
        }

        private val MIGRATION_9_10 = object : androidx.room.migration.Migration(9, 10) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `performance_predictions` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `userId` TEXT NOT NULL, `predictedScore` REAL NOT NULL, `confidence` TEXT NOT NULL, `riskLevel` TEXT NOT NULL, `readinessStatus` TEXT NOT NULL, `generatedAt` INTEGER NOT NULL)")
            }
        }

        private val MIGRATION_10_11 = object : androidx.room.migration.Migration(10, 11) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `study_plans` (`id` TEXT NOT NULL, `generatedAt` INTEGER NOT NULL, `examDate` INTEGER, `dailyTimeGoalMinutes` INTEGER NOT NULL, `planJson` TEXT NOT NULL, `isActive` INTEGER NOT NULL, PRIMARY KEY(`id`))")
            }
        }

        private val MIGRATION_11_12 = object : androidx.room.migration.Migration(11, 12) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `revision_queue` (`topic` TEXT NOT NULL, `nextReviewAt` INTEGER NOT NULL, `intervalDays` INTEGER NOT NULL, `retentionProbability` REAL NOT NULL, `lastUpdatedAt` INTEGER NOT NULL, PRIMARY KEY(`topic`))")
            }
        }

        private val MIGRATION_12_13 = object : androidx.room.migration.Migration(12, 13) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `daily_tasks` (`id` TEXT NOT NULL, `topic` TEXT NOT NULL, `taskType` TEXT NOT NULL, `estimatedMinutes` INTEGER NOT NULL, `priority` TEXT NOT NULL, `dueAt` INTEGER NOT NULL, `completed` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, PRIMARY KEY(`id`))")
            }
        }

        private val MIGRATION_13_14 = object : androidx.room.migration.Migration(13, 14) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `exam_templates` (`id` TEXT NOT NULL, `title` TEXT NOT NULL, `totalDurationMinutes` INTEGER NOT NULL, `templateJson` TEXT NOT NULL, `createdAt` INTEGER NOT NULL, PRIMARY KEY(`id`))")
                database.execSQL("CREATE TABLE IF NOT EXISTS `mock_exam_history` (`id` TEXT NOT NULL, `templateId` TEXT NOT NULL, `score` REAL NOT NULL, `durationMinutes` INTEGER NOT NULL, `completedAt` INTEGER NOT NULL, `attemptJson` TEXT NOT NULL, PRIMARY KEY(`id`))")
            }
        }

        private val MIGRATION_14_15 = object : androidx.room.migration.Migration(14, 15) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `exam_integrity_events` (`id` TEXT NOT NULL, `examId` TEXT NOT NULL, `eventType` TEXT NOT NULL, `timestamp` INTEGER NOT NULL, PRIMARY KEY(`id`))")
                database.execSQL("CREATE TABLE IF NOT EXISTS `exam_active_sessions` (`examId` TEXT NOT NULL, `templateId` TEXT NOT NULL, `currentQuestionIndex` INTEGER NOT NULL, `remainingTimeSeconds` INTEGER NOT NULL, `answersJson` TEXT NOT NULL, `violationCount` INTEGER NOT NULL, `lastUpdatedAt` INTEGER NOT NULL, PRIMARY KEY(`examId`))")
            }
        }

        private val MIGRATION_15_16 = object : androidx.room.migration.Migration(15, 16) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `exam_timer_state` (`examId` TEXT NOT NULL, `remainingSeconds` INTEGER NOT NULL, `lastUpdatedAt` INTEGER NOT NULL, `sectionIndex` INTEGER NOT NULL, PRIMARY KEY(`examId`))")
            }
        }

        private val MIGRATION_16_17 = object : androidx.room.migration.Migration(16, 17) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `exam_analytics` (`examId` TEXT NOT NULL, `score` REAL NOT NULL, `averageTimePerQuestion` REAL NOT NULL, `stressIndex` REAL NOT NULL, `readinessStatus` TEXT NOT NULL, `generatedAt` INTEGER NOT NULL, PRIMARY KEY(`examId`))")
            }
        }

        private val MIGRATION_17_18 = object : androidx.room.migration.Migration(17, 18) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `marketplace_exams` (`id` TEXT NOT NULL, `templateId` TEXT NOT NULL, `title` TEXT NOT NULL, `subject` TEXT NOT NULL, `description` TEXT NOT NULL, `creatorId` TEXT NOT NULL, `price` REAL NOT NULL, `visibility` TEXT NOT NULL, `publishedAt` INTEGER NOT NULL, PRIMARY KEY(`id`))")
                database.execSQL("CREATE TABLE IF NOT EXISTS `creator_revenue` (`creatorId` TEXT NOT NULL, `totalSales` INTEGER NOT NULL, `totalRevenue` REAL NOT NULL, `lastUpdatedAt` INTEGER NOT NULL, PRIMARY KEY(`creatorId`))")
            }
        }

        private val MIGRATION_18_19 = object : androidx.room.migration.Migration(18, 19) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                // Add columns to marketplace_exams
                database.execSQL("ALTER TABLE `marketplace_exams` ADD COLUMN `creatorName` TEXT NOT NULL DEFAULT 'Internal'")
                database.execSQL("ALTER TABLE `marketplace_exams` ADD COLUMN `downloads` INTEGER NOT NULL DEFAULT 0")
                database.execSQL("ALTER TABLE `marketplace_exams` ADD COLUMN `rating` REAL NOT NULL DEFAULT 5.0")
                database.execSQL("ALTER TABLE `marketplace_exams` ADD COLUMN `completionRate` REAL NOT NULL DEFAULT 1.0")
                database.execSQL("ALTER TABLE `marketplace_exams` ADD COLUMN `difficulty` TEXT NOT NULL DEFAULT 'MEDIUM'")
                
                // Create marketplace_interactions table
                database.execSQL("CREATE TABLE IF NOT EXISTS `marketplace_interactions` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `examId` TEXT NOT NULL, `userId` TEXT NOT NULL, `action` TEXT NOT NULL, `timestamp` INTEGER NOT NULL)")
            }
        }
        private val MIGRATION_19_20 = object : androidx.room.migration.Migration(19, 20) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `study_streak` (`userId` TEXT NOT NULL, `currentStreak` INTEGER NOT NULL, `longestStreak` INTEGER NOT NULL, `lastActiveDate` INTEGER NOT NULL, `graceDaysUsedThisWeek` INTEGER NOT NULL DEFAULT 0, `lastGraceDayUsedAt` INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(`userId`))")
            }
        }
        private val MIGRATION_20_21 = object : androidx.room.migration.Migration(20, 21) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `daily_insights` (`id` TEXT NOT NULL, `message` TEXT NOT NULL, `priority` TEXT NOT NULL, `createdAt` INTEGER NOT NULL, PRIMARY KEY(`id`))")
            }
        }
        private val MIGRATION_21_22 = object : androidx.room.migration.Migration(21, 22) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `auto_generated_tests` (`id` TEXT NOT NULL, `topic` TEXT NOT NULL, `testId` INTEGER NOT NULL, `createdAt` INTEGER NOT NULL, `scheduledFor` INTEGER NOT NULL, `isCompleted` INTEGER NOT NULL, PRIMARY KEY(`id`))")
            }
        }
        private val MIGRATION_22_23 = object : androidx.room.migration.Migration(22, 23) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `ai_cost_usage` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `userId` TEXT NOT NULL, `modelName` TEXT NOT NULL, `tokensUsed` INTEGER NOT NULL, `estimatedCost` REAL NOT NULL, `timestamp` INTEGER NOT NULL)")
            }
        }
        private val MIGRATION_23_24 = object : androidx.room.migration.Migration(23, 24) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `referrals` (`inviteeId` TEXT NOT NULL, `inviterId` TEXT NOT NULL, `rewardIssued` INTEGER NOT NULL, `rewardType` TEXT NOT NULL, `timestamp` INTEGER NOT NULL, PRIMARY KEY(`inviteeId`))")
            }
        }
        private val MIGRATION_24_25 = object : androidx.room.migration.Migration(24, 25) {
            override fun migrate(database: androidx.sqlite.db.SupportSQLiteDatabase) {
                database.execSQL("CREATE TABLE IF NOT EXISTS `feature_flags` (`featureName` TEXT NOT NULL, `enabled` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL, PRIMARY KEY(`featureName`))")
            }
        }
    }
}
