package com.shiva.magics.data.local

import androidx.room.*
import kotlinx.coroutines.flow.Flow

@Entity(tableName = "auto_generated_tests")
data class AutoGeneratedTestEntity(
    @PrimaryKey val id: String,
    val topic: String,
    val testId: Long, // Reference to TestHistoryEntity.id
    val createdAt: Long = System.currentTimeMillis(),
    val scheduledFor: Long,
    val isCompleted: Boolean = false
)

@Dao
interface AutoGeneratedTestDao {
    @Query("SELECT * FROM auto_generated_tests WHERE isCompleted = 0 ORDER BY scheduledFor ASC")
    fun getPendingAutoTests(): Flow<List<AutoGeneratedTestEntity>>

    @Query("SELECT * FROM auto_generated_tests WHERE isCompleted = 0")
    suspend fun getPendingAutoTestsOnce(): List<AutoGeneratedTestEntity>

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAutoTest(autoTest: AutoGeneratedTestEntity)

    @Query("UPDATE auto_generated_tests SET isCompleted = 1 WHERE testId = :testId")
    suspend fun markCompleted(testId: Long)

    @Query("DELETE FROM auto_generated_tests WHERE createdAt < :timestamp")
    suspend fun clearOldLog(timestamp: Long)
}
