package com.shiva.magics.util

import com.shiva.magics.data.local.AICostDao
import com.shiva.magics.data.local.AICostUsageEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.Calendar

/**
 * Phase 9 — Production Hardening: AI Cost Monitor & Guardrails
 * Prevents runaway API costs and ensures system stability at scale.
 */
object AICostMonitor {

    private const val DAILY_COST_THRESHOLD = 0.50 // Max $0.50 per day per user
    private const val COST_PER_TOKEN = 0.00000015 // Approx cost for Gemini 2.0 Flash ($0.15 per 1M)

    /**
     * Records token usage and returns true if within budget.
     */
    suspend fun recordAndCheckBudget(
        dao: AICostDao,
        userId: String,
        modelName: String,
        tokensUsed: Int
    ): Boolean = withContext(Dispatchers.IO) {
        
        val estimatedCost = tokensUsed * COST_PER_TOKEN
        
        // 1. Check Daily Limit
        val calendar = Calendar.getInstance()
        calendar.set(Calendar.HOUR_OF_DAY, 0)
        calendar.set(Calendar.MINUTE, 0)
        calendar.set(Calendar.SECOND, 0)
        val todayStart = calendar.timeInMillis

        val totalDailyCost = dao.getCostForPeriod(todayStart) ?: 0.0
        
        if (totalDailyCost + estimatedCost > DAILY_COST_THRESHOLD) {
            return@withContext false
        }
        
        // 2. Record Usage
        dao.insertUsage(
            AICostUsageEntity(
                userId = userId,
                modelName = modelName,
                tokensUsed = tokensUsed,
                estimatedCost = estimatedCost
            )
        )

        return@withContext true
    }

    // ── In-memory request ledger (bounded, non-durable) ──────────────────────
    // Primary durable accounting is in recordAndCheckBudget via AICostDao.
    // This ledger covers callers (e.g. AiProviderManager) that don't have DAO.
    data class RequestRecord(
        val modelName:     String,
        val source:        String,
        val questionCount: Int,
        val estimatedTokens: Int,
        val estimatedCost:   Double,
        val timestamp:     Long = System.currentTimeMillis()
    )

    private const val MAX_LEDGER = 200
    private val requestLedger = ArrayDeque<RequestRecord>(MAX_LEDGER)
    private val ledgerLock = Any()

    /**
     * Records a completed AI request in the in-memory ledger.
     * Estimates token usage from question count (≈ 500 tokens/question average).
     * Does NOT enforce budget — call recordAndCheckBudget() for that.
     */
    fun recordRequest(modelName: String, source: String, count: Int) {
        val estimatedTokens = count * 500
        val estimatedCost   = estimatedTokens * COST_PER_TOKEN
        val record = RequestRecord(
            modelName      = modelName,
            source         = source,
            questionCount  = count,
            estimatedTokens = estimatedTokens,
            estimatedCost   = estimatedCost
        )
        synchronized(ledgerLock) {
            requestLedger.addLast(record)
            if (requestLedger.size > MAX_LEDGER) requestLedger.removeFirst()
        }
        android.util.Log.d(
            "AICostMonitor",
            "📝 recordRequest: model=$modelName src=$source qs=$count " +
            "tokens≈$estimatedTokens cost≈\$${"%.6f".format(estimatedCost)}"
        )
    }

    /** Returns a snapshot of the in-memory ledger for debugging / dashboards. */
    fun getLedgerSnapshot(): List<RequestRecord> =
        synchronized(ledgerLock) { requestLedger.toList() }

    /** Total estimated cost across all ledger entries. */
    fun getLedgerTotalCost(): Double =
        synchronized(ledgerLock) { requestLedger.sumOf { it.estimatedCost } }
}

/**
 * Automation Guardrails
 */
object GuardrailSystem {

    private const val MAX_AUTO_TESTS_PER_DAY = 2

    /**
     * Checks if autonomous action is allowed.
     */
    suspend fun canGenerateAutoTest(
        db: com.shiva.magics.data.local.AppDatabase,
        topic: String
    ): Boolean {
        val calendar = Calendar.getInstance()
        calendar.set(Calendar.HOUR_OF_DAY, 0)
        calendar.set(Calendar.MINUTE, 0)
        calendar.set(Calendar.SECOND, 0)
        val todayStart = calendar.timeInMillis
        
        // Rule 1: Max 2 auto tests per day total
        val todayTests = db.autoGeneratedTestDao().getPendingAutoTestsOnce()
            .filter { it.createdAt > todayStart }
        
        if (todayTests.size >= MAX_AUTO_TESTS_PER_DAY) return false
        
        // Rule 2: Don't repeat same topic in 24 hours
        if (todayTests.any { it.topic == topic }) return false

        return true
    }
}
