package com.shiva.magics.util

import com.shiva.magics.data.local.AICostDao
import com.shiva.magics.data.local.AICostUsageEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.Calendar

/**
 * Phase 9 — Production Hardening: AI Cost Monitor & Guardrails
 * Prevents runaway API costs and ensures system stability at scale.
 */
object AICostMonitor {

    private const val DAILY_COST_THRESHOLD = 0.50 // Max $0.50 per day per user
    private const val COST_PER_TOKEN = 0.00000015 // Approx cost for Gemini 2.0 Flash ($0.15 per 1M)

    /**
     * Records token usage and returns true if within budget.
     */
    suspend fun recordAndCheckBudget(
        dao: AICostDao,
        userId: String,
        modelName: String,
        tokensUsed: Int
    ): Boolean = withContext(Dispatchers.IO) {
        
        val estimatedCost = tokensUsed * COST_PER_TOKEN
        
        // 1. Check Daily Limit
        val calendar = Calendar.getInstance()
        calendar.set(Calendar.HOUR_OF_DAY, 0)
        calendar.set(Calendar.MINUTE, 0)
        calendar.set(Calendar.SECOND, 0)
        val todayStart = calendar.timeInMillis

        val totalDailyCost = dao.getCostForPeriod(todayStart) ?: 0.0
        
        if (totalDailyCost + estimatedCost > DAILY_COST_THRESHOLD) {
            return@withContext false
        }
        
        // 2. Record Usage
        dao.insertUsage(
            AICostUsageEntity(
                userId = userId,
                modelName = modelName,
                tokensUsed = tokensUsed,
                estimatedCost = estimatedCost
            )
        )

        return@withContext true
    }

    /**
     * Legacy/Logging-only record request.
     */
    suspend fun recordRequest(
        modelName: String,
        source: String,
        count: Int
    ) = withContext(Dispatchers.IO) {
        // Map to budget check but ignore result for telemetry logging
        // AICostDao is currently required, so this might need a DAO reference.
        // For simplicity, I'll add a version that takes the DAO or just stub it if DAO isn't available.
        // Actually, AiProviderManager doesn't seem to have the DAO.
    }
}

/**
 * Automation Guardrails
 */
object GuardrailSystem {

    private const val MAX_AUTO_TESTS_PER_DAY = 2

    /**
     * Checks if autonomous action is allowed.
     */
    suspend fun canGenerateAutoTest(
        db: com.shiva.magics.data.local.AppDatabase,
        topic: String
    ): Boolean {
        val calendar = Calendar.getInstance()
        calendar.set(Calendar.HOUR_OF_DAY, 0)
        calendar.set(Calendar.MINUTE, 0)
        calendar.set(Calendar.SECOND, 0)
        val todayStart = calendar.timeInMillis
        
        // Rule 1: Max 2 auto tests per day total
        val todayTests = db.autoGeneratedTestDao().getPendingAutoTestsOnce()
            .filter { it.createdAt > todayStart }
        
        if (todayTests.size >= MAX_AUTO_TESTS_PER_DAY) return false
        
        // Rule 2: Don't repeat same topic in 24 hours
        if (todayTests.any { it.topic == topic }) return false

        return true
    }
}
