package com.shiva.magics.util

import com.shiva.magics.data.local.*
import com.shiva.magics.data.remote.GeminiService
import com.shiva.magics.data.repository.TestRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.util.UUID

/**
 * Phase 8 — Autonomous Learning Agent
 * Takes initiative to generate practice tests based on user performance gaps.
 */
object AutonomousAgent {

    /**
     * Runs the autonomous learning loop.
     * Checks for weaknesses and generates practice content if needed.
     */
    suspend fun runAutonomousLoop(
        db: AppDatabase,
        repository: TestRepository,
        geminiService: GeminiService
    ) = withContext(Dispatchers.IO) {
        
        // 0. Launch Safeguard: Check if feature is enabled
        if (!ConfigManager.isFeatureEnabled(db.featureFlagDao(), ConfigManager.FEATURE_AUTO_GENERATION)) {
            return@withContext
        }

        val masteryDao = db.topicMasteryDao()
        val autoDao = db.autoGeneratedTestDao()
        
        // 1. Identify critical weaknesses (Mastery < 50%)
        val weakTopics = masteryDao.getAllMasteryOnce().filter { it.masteryLevel < 50f }
        if (weakTopics.isEmpty()) return@withContext

        // 2. Select the weakest topic
        val targetTopic = weakTopics.minBy { it.masteryLevel }
        
        // 3. Automation Guardrails
        if (!GuardrailSystem.canGenerateAutoTest(db, targetTopic.topic)) return@withContext

        // 4. Trigger AI Question Generation
        val result = geminiService.generatePracticeQuestions(targetTopic.topic)
        
        result.onSuccess { questions ->
            if (questions.isEmpty()) return@onSuccess
            
            // 5. Save as a new Test in TestHistory
            val testId = repository.saveTest(
                title = "Auto Practice: ${targetTopic.topic}",
                category = "Practice",
                questions = questions
            )
            
            // 6. Record in Autonomous Log
            val autoTest = AutoGeneratedTestEntity(
                id = UUID.randomUUID().toString(),
                topic = targetTopic.topic,
                testId = testId,
                scheduledFor = System.currentTimeMillis() + (1000 * 60 * 60) // Schedule for 1 hour later
            )
            autoDao.insertAutoTest(autoTest)
            
            // 7. Telemetry
            TelemetryCollector.record(TelemetryCollector.EventType.STREAK_INCREMENTED, "auto_test_generated", 1.0)
        }
    }
}
